// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzmbxoumjrlfssdbgfww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6bWJ4b3VtanJsZnNzZGJnZnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTI4MjMsImV4cCI6MjA2MTA4ODgyM30.SVbAgyN9UeNECGwHWERQar8cvVvpfAcPMaIxmjW7OMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);